volumes:
  mariadb_data:

services:
  db:
    image: mariadb:11.3.2
    environment:
      MYSQL_ROOT_PASSWORD: AtxxCT3koox915FS
      MYSQL_DATABASE: fleet
      MYSQL_USER: fleet_user
      MYSQL_PASSWORD: fleet_password
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_USER: fleet_user
      PMA_PASSWORD: fleet_password
    ports:
      - '9091:80'
